services:
  - type: web
    name: studyzone-backend
    env: node
    plan: free
    repo: https://github.com/MonsieurChips/Study-Zone.git
    rootDir: Fullstack-BE-main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false